In [1]:
from cvxopt import matrix, solvers
import numpy as np

# Nhập hàm chuẩn, in ra giá trị tối ưu và nghiệm tối ưu

In [2]:
def input_matrix():

  # input matrix c: hàm mục tiêu
  print("Input matrix c: ")
  row_c = int(input("Enter the number of rows of matrix c:"))
  print("Enter the entries in a single column (separated by space): ")
  c = list(map(float, input().split()))
  matrix_c = matrix(c, (row_c, 1)) # Directly create cvxopt matrix
  print(f'matrix c is:\n {matrix_c}\n')

  # input matrix A
  print("Input matrix A: ")
  row_A = int(input("Enter the number of rows of matrix A:"))
  col_A = int(input("Enter the number of columns of matrix A:"))
  print("Enter the entries in a single column (separated by space): ")
  A = list(map(float, input().split()))
  matrix_A = matrix(A, (row_A, col_A)) # Directly create cvxopt matrix
  print(f'matrix A is:\n {matrix_A}\n')

  # input matrix b: contrains
  print("Input matrix b: ")
  row_b = int(input("Enter the number of rows of matrix b:"))
  print("Enter the entries in a single column (separated by space): ")
  # col_b = int(input("Enter the number of columns of matrix b:"))
  b = list(map(float, input().split()))
  matrix_b = matrix(b, (row_b, 1)) # Directly create cvxopt matrix
  print(f'matrix b is:\n {matrix_b}\n')
  return matrix_c, matrix_A, matrix_b

matrix_c, matrix_A, matrix_b = input_matrix()
# print(f'matrix c is:\n{matrix_c}\n')
# print(f'matrix A is:\n{matrix_A}\n')
# print(f'matrix b is:\n{matrix_b}\n')


Input matrix c: 
Enter the number of rows of matrix c:4
Enter the entries in a single column (separated by space): 
-1 -2 -3 -4
matrix c is:
 [-1.00e+00]
[-2.00e+00]
[-3.00e+00]
[-4.00e+00]


Input matrix A: 
Enter the number of rows of matrix A:6
Enter the number of columns of matrix A:4
Enter the entries in a single column (separated by space): 
4 1 -1 0 0 0 9 1 0 -1 0 0 7 3 0 0 -1 0 10 4 0 0 0 -1
matrix A is:
 [ 4.00e+00  9.00e+00  7.00e+00  1.00e+01]
[ 1.00e+00  1.00e+00  3.00e+00  4.00e+00]
[-1.00e+00  0.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00 -1.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00 -1.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00  0.00e+00 -1.00e+00]


Input matrix b: 
Enter the number of rows of matrix b:6
Enter the entries in a single column (separated by space): 
6 4 0 0 0 0
matrix b is:
 [ 6.00e+00]
[ 4.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]




In [3]:
def solver():
  show_progress = input("Do you want to show progress? [Y/N] ")
  if show_progress == 'Y' or show_progress == "Yes" or show_progress == "YES" or show_progress == "yes" or show_progress == "y":
    solvers.options['show_progress'] = True
    solution = solvers.lp(matrix_c, matrix_A, matrix_b)
    print('Optimal solution:\n', solution['x'].T)
    print('optimal value:\n',solution['primal objective'])
    return solution
  else:
    solvers.options['show_progress'] = False
    solution = solvers.lp(matrix_c, matrix_A, matrix_b)
    print('Optimal solution:\n', solution['x'].T)
    print('optimal value:\n',solution['primal objective'])
    return solution

result = solver()
print(result)

Do you want to show progress? [Y/N] Y
     pcost       dcost       gap    pres   dres   k/t
 0: -3.2000e+00 -1.4825e+01  1e+01  5e-01  4e+00  1e+00
 1: -2.9726e+00 -5.0587e+00  1e+00  1e-01  8e-01  4e-01
 2: -2.5691e+00 -2.8798e+00  2e-01  1e-02  1e-01  4e-03
 3: -2.5716e+00 -2.5783e+00  4e-03  3e-04  2e-03  2e-04
 4: -2.5714e+00 -2.5715e+00  4e-05  3e-06  2e-05  2e-06
 5: -2.5714e+00 -2.5714e+00  4e-07  3e-08  2e-07  2e-08
 6: -2.5714e+00 -2.5714e+00  4e-09  3e-10  2e-09  2e-10
Optimal solution found.
Optimal solution:
 [ 6.07e-11 -6.22e-10  8.57e-01  1.56e-09]

optimal value:
 -2.5714285716321097
{'x': <4x1 matrix, tc='d'>, 'y': <0x1 matrix, tc='d'>, 's': <6x1 matrix, tc='d'>, 'z': <6x1 matrix, tc='d'>, 'status': 'optimal', 'gap': 4.328590845452309e-09, 'relative gap': 1.6833408842093216e-09, 'primal objective': -2.5714285716321097, 'dual objective': -2.571428578318077, 'primal infeasibility': 2.6516912730737535e-10, 'dual infeasibility': 2.170094455089397e-09, 'primal slack': 1.5814